language: cpp
sudo: required
script:
  - unzip src/sqlite3.h.zip -d src
  - unzip src/sqlite3.c.zip -d src
  - make
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - unzip