version: 1.0.{build}
image: Visual Studio 2017

before_build:
- ps: >-
    Expand-Archive src/sqlite3.h.zip -DestinationPath src

    Expand-Archive src/sqlite3.c.zip -DestinationPath src

build:
- ps: >-
    msbuild C:\projects\orm-lite\sample\sample.vcxproj

    msbuild C:\projects\orm-lite\test\test.vcxproj

test_script:
- ps: >-
    C:\projects\orm-lite\test\x64\Debug\Sample\Sample.exe

    C:\projects\orm-lite\test\x64\Debug\Test\Test.exe